{
  lib,
  nixPiModulesNoShell,
  mkTestFilesystems,
  mkManagedUserConfig,
  ...
}:

let
  finalizeInstall = ../../core/scripts/nixpi-install-finalize.sh;
in
{
  name = "nixpi-system-flake";

  nodes.machine =
    { pkgs, ... }:
    {
      imports = nixPiModulesNoShell ++ [
        mkTestFilesystems
      ];
      nixpi.install.enable = true;
      nixpi.install.repoUrl = "file:///var/lib/nixpi-source";
      nixpi.install.repoBranch = "main";

      networking.hostName = "system-flake-test";
      system.stateVersion = "25.05";
      environment.systemPackages = [ pkgs.git ];

      environment.etc = {
        "system-flake-marker".text = "preserved";
        "nixos/configuration.nix".text = ''
          { ... }:
          {
            networking.hostName = "system-flake-test";
          }
        '';
        "nixos/hardware-configuration.nix".text = ''
          { ... }:
          {}
        '';
      };

      system.activationScripts.nixpi-test-install-seed = lib.stringAfter [ "users" ] ''
        if [ ! -d /var/lib/nixpi-source/.git ]; then
          rm -rf /var/lib/nixpi-source
          install -d -m 0755 /var/lib/nixpi-source
          cp -R ${../../.}/. /var/lib/nixpi-source/
          chmod -R u+rwX /var/lib/nixpi-source
          ${lib.getExe pkgs.git} -C /var/lib/nixpi-source init -b main
          ${lib.getExe pkgs.git} -C /var/lib/nixpi-source add .
          ${lib.getExe pkgs.git} -C /var/lib/nixpi-source -c user.name='Test User' -c user.email='test@example.com' commit -m 'seed repo'
        fi
      '';

    }
    // (mkManagedUserConfig { username = "pi"; });

  testScript = ''
    machine = machines[0]
    nixpkgs_url = "path:/tmp/host-nixpkgs"
    stable_release = "25.11"

    machine.start()
    machine.wait_for_unit("multi-user.target", timeout=300)

    machine.succeed("test -f /etc/system-flake-marker")
    machine.succeed("grep -q 'preserved' /etc/system-flake-marker")
    machine.succeed("/run/current-system/sw/bin/bash ${finalizeInstall} file:///var/lib/nixpi-source main pi system-flake-test UTC us")
    machine.succeed("test -d /srv/nixpi/.git")
    machine.succeed("test -f /srv/nixpi/flake.nix")
    machine.succeed("test -f /etc/nixos/flake.nix")
    machine.succeed("grep -q 'nixosConfigurations.nixos' /etc/nixos/flake.nix")
    machine.succeed("grep -q 'networking.hostName = \"system-flake-test\";' /etc/nixos/flake.nix")
    machine.succeed("grep -q 'github:NixOS/nixpkgs/nixos-" + stable_release + "' /etc/nixos/flake.nix")
    machine.succeed("grep -q 'nixpi.inputs.nixpkgs.follows = \"nixpkgs\";' /etc/nixos/flake.nix")
    machine.succeed("grep -q 'path:/srv/nixpi' /etc/nixos/flake.nix")

    machine.succeed("printf '%s\n' '# Generated by NixPI bootstrap' '{' '  description = \"NixPI system flake\";' '  inputs = {' '    nixpkgs.url = \"github:NixOS/nixpkgs/nixos-unstable\";' '    nixpi.url = \"path:/srv/nixpi\";' '  };' '}' > /etc/nixos/flake.nix")
    machine.succeed("/run/current-system/sw/bin/bash ${finalizeInstall} file:///var/lib/nixpi-source main pi system-flake-test UTC us")
    machine.succeed("grep -q 'github:NixOS/nixpkgs/nixos-" + stable_release + "' /etc/nixos/flake.nix")
    machine.succeed("grep -q 'nixpi.inputs.nixpkgs.follows = \"nixpkgs\";' /etc/nixos/flake.nix")
    machine.succeed("grep -q 'nixosConfigurations.nixos' /etc/nixos/flake.nix")
    machine.succeed("grep -q 'path:/srv/nixpi' /etc/nixos/flake.nix")

    machine.succeed("rm -f /etc/nixos/flake.nix")
    machine.succeed("env NIXPI_NIXPKGS_FLAKE_URL='" + nixpkgs_url + "' /run/current-system/sw/bin/bash ${finalizeInstall} file:///var/lib/nixpi-source main pi system-flake-test UTC us")
    machine.succeed("grep -q '" + nixpkgs_url + "' /etc/nixos/flake.nix")
    machine.succeed("grep -q 'nixpi.inputs.nixpkgs.follows = \"nixpkgs\";' /etc/nixos/flake.nix")
    machine.succeed("grep -q 'nixosConfigurations.nixos' /etc/nixos/flake.nix")
    machine.succeed("test -f /etc/system-flake-marker")
    machine.succeed("grep -q 'preserved' /etc/system-flake-marker")

    print("nixpi-system-flake test passed!")
  '';
}
