import { describe, expect, it } from "vitest";
import { generateVhostConfig, vhostConfigPath } from "../../lib/nginx.js";

describe("generateVhostConfig", () => {
	it("generates basic vhost without websocket", () => {
		const config = generateVhostConfig({
			serviceName: "cinny",
			serverName: "cinny.bloom.mesh",
			upstreamPort: 18810,
		});
		expect(config).toContain("server_name cinny.bloom.mesh;");
		expect(config).toContain("proxy_pass http://127.0.0.1:18810;");
		expect(config).toContain("proxy_set_header Host $host;");
		expect(config).not.toContain("Upgrade");
		expect(config).not.toContain("client_max_body_size");
	});

	it("includes websocket headers when enabled", () => {
		const config = generateVhostConfig({
			serviceName: "dufs",
			serverName: "dufs.bloom.mesh",
			upstreamPort: 5000,
			websocket: true,
		});
		expect(config).toContain("proxy_http_version 1.1;");
		expect(config).toContain("proxy_set_header Upgrade $http_upgrade;");
		expect(config).toContain("proxy_set_header Connection $connection_upgrade;");
	});

	it("includes client_max_body_size when set", () => {
		const config = generateVhostConfig({
			serviceName: "dufs",
			serverName: "dufs.bloom.mesh",
			upstreamPort: 5000,
			maxBodySize: "0",
		});
		expect(config).toContain("client_max_body_size 0;");
	});

	it("includes auto-generated comment", () => {
		const config = generateVhostConfig({
			serviceName: "test-svc",
			serverName: "test-svc.bloom.mesh",
			upstreamPort: 9090,
		});
		expect(config).toContain("# Auto-generated by Bloom for service: test-svc");
	});

	it("combines websocket and maxBodySize", () => {
		const config = generateVhostConfig({
			serviceName: "webdav",
			serverName: "webdav.bloom.mesh",
			upstreamPort: 5000,
			websocket: true,
			maxBodySize: "0",
		});
		expect(config).toContain("proxy_http_version 1.1;");
		expect(config).toContain("client_max_body_size 0;");
		expect(config).toContain("server_name webdav.bloom.mesh;");
	});
});

describe("vhostConfigPath", () => {
	it("returns correct path with bloom- prefix", () => {
		expect(vhostConfigPath("cinny")).toBe("/etc/nginx/conf.d/bloom-cinny.conf");
	});

	it("handles hyphenated names", () => {
		expect(vhostConfigPath("code-server")).toBe("/etc/nginx/conf.d/bloom-code-server.conf");
	});
});
