/** Nginx vhost generation and management for dynamic subdomain routing. */
import { run } from "./exec.js";
import { createLogger } from "./shared.js";

const log = createLogger("nginx");

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface VhostOptions {
	serviceName: string;
	serverName: string;
	upstreamPort: number;
	websocket?: boolean;
	maxBodySize?: string;
}

export interface NginxResult {
	ok: boolean;
	error?: string;
}

// ---------------------------------------------------------------------------
// Vhost config generation
// ---------------------------------------------------------------------------

/** Generate an nginx `server {}` block for a service subdomain. */
export function generateVhostConfig(opts: VhostOptions): string {
	const { serverName, upstreamPort, websocket, maxBodySize } = opts;
	const lines = [
		`# Auto-generated by Bloom for service: ${opts.serviceName}`,
		`server {`,
		`    listen 80;`,
		`    server_name ${serverName};`,
		``,
		`    location / {`,
		`        proxy_pass http://127.0.0.1:${upstreamPort};`,
		`        proxy_set_header Host $host;`,
		`        proxy_set_header X-Real-IP $remote_addr;`,
		`        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`,
		`        proxy_set_header X-Forwarded-Proto $scheme;`,
	];

	if (websocket) {
		lines.push(`        proxy_http_version 1.1;`);
		lines.push(`        proxy_set_header Upgrade $http_upgrade;`);
		lines.push(`        proxy_set_header Connection $connection_upgrade;`);
	}

	if (maxBodySize) {
		lines.push(`        client_max_body_size ${maxBodySize};`);
	}

	lines.push(`    }`);
	lines.push(`}`);
	lines.push(``);

	return lines.join("\n");
}

/** Return the nginx config file path for a service. */
export function vhostConfigPath(serviceName: string): string {
	return `/etc/nginx/conf.d/bloom-${serviceName}.conf`;
}

// ---------------------------------------------------------------------------
// File operations (require sudo)
// ---------------------------------------------------------------------------

/** Write a vhost config file via `sudo tee`. */
export async function writeVhostConfig(
	serviceName: string,
	config: string,
	signal?: AbortSignal,
): Promise<NginxResult> {
	const path = vhostConfigPath(serviceName);
	const result = await run("sudo", ["tee", path], signal, undefined, undefined, config);
	if (result.exitCode !== 0) {
		log.error("failed to write vhost config", { path, stderr: result.stderr });
		return { ok: false, error: `Failed to write ${path}: ${result.stderr}` };
	}
	log.info("wrote vhost config", { path });
	return { ok: true };
}

/** Remove a vhost config file and reload nginx. */
export async function removeVhostConfig(serviceName: string, signal?: AbortSignal): Promise<NginxResult> {
	const path = vhostConfigPath(serviceName);
	const rm = await run("sudo", ["rm", "-f", path], signal);
	if (rm.exitCode !== 0) {
		return { ok: false, error: `Failed to remove ${path}: ${rm.stderr}` };
	}
	return reloadNginx(signal);
}

/** Reload nginx configuration via `sudo nginx -s reload`. */
export async function reloadNginx(signal?: AbortSignal): Promise<NginxResult> {
	const result = await run("sudo", ["nginx", "-s", "reload"], signal);
	if (result.exitCode !== 0) {
		log.error("nginx reload failed", { stderr: result.stderr });
		return { ok: false, error: `nginx reload failed: ${result.stderr}` };
	}
	log.info("nginx reloaded");
	return { ok: true };
}
